### PR TITLE
Refactor module

### PR DESCRIPTION
**Pull request by fntz**
Hi.
I added `Forwardable` module for reduce the complexity.

### CODE REVIEW

**Comment by cmichon** [comment]
Interesting, as I was looking at some delegation code recently but did not realise the possibility to use Forwardable.

I have more refactoring possible around @tree, not needed due to some MapDB internals.

I should merge your changes shortly, thanks again.

**Comment by fntz** [comment]
Ok. thanks

**Comment by cmichon** [comment]
Regarding "when you add other methods or vars it will just change", as I said I agree it's not DRY enough.

On your rewriting the method with the initialize, please go ahead. I did a lot of trick in the class methods and variables, not so much in the instances. If you feel the project would benefit from it, please go ahead, I'll try it out and merge it (quite likely).

**Comment by fntz** [comment]
ok :)

**Pull request merged**
